Core/urls.py
from django.urls import path

app_name = 'Core'

urlpatterns = []

P001/urls.py
from django.urls import path
from P001.views import home, kashta, bladalnoor, batinjan, partenership

app_name = 'P001'

urlpatterns = [
    path('', home.show, name='home'),
    path('kashta/home', kashta.home, name='kashta-home'),
    path('bladalnoor/home', bladalnoor.home, name='bladalnoor-home'),
    path('batinjan/home', batinjan.home, name='batinjan-home'),
    path('partenership/home', partenership.home, name='partenership-home'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from P000.views import home

urlpatterns = [

    path('', home.show, name='website-home'),

    path('Core/', include('Core.urls')), # Core
    path('login/home/', include('P000.urls')), # P000
    path('user/dashboard/', include('P001.urls')), # P001
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Use static() to add url mapping to serve static files during development (only)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Core/forms.py
from django.contrib.gis import forms as gis_form
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.forms.fields import CheckboxInput

from colorful.fields import RGBColorField
from leaflet.forms.widgets import LeafletWidget

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from Core.models.Organization import Organization
from Core.models.OrganizationUser import OrganizationUser
from Core.models.Place import Place
from Core.models.Document import Document
from Core.models.WF_Chart import WF_Chart
from Core.models.WF_Action import WF_Action
from Core.models.WF_Input import WF_Input
from Core.models.WF_Track import WF_Track
from Core.models.WF_Data import WF_Data
from Core.models.WF_Dump import WF_Dump
from Core.models.SheetParagraph import SheetParagraph
from Core.models.Component import Component
from Core.models.Paragraph import Paragraph
from Core.models.Parameter import Parameter
from Core.models.Permit import Permit
from Core.models.Feature import Feature
from Core.models.Procedure import Procedure
from Core.models.Sheet import Sheet
from Core.models.Element import Element
from Core.models.Fact import Fact
from Core.models.Datum import Datum
from Core.models.Analyze import Analyze
from Core.models.Version import Version
from Core.models.Refinement import Refinement
from P003.models.Unit import Unit
from P003.models.Vacant import Vacant

from Core.cons.WORKFLOW import list_of_executor_types
from Core.cons.WORKFLOW import list_of_input_choices
from Core.cons.WORKFLOW import list_of_action_types
from Core.cons.WORKFLOW import list_of_executions_status
from Core.cons.WORKFLOW import list_of_action_categories
from Core.cons.WORKFLOW import list_of_notification_types
from Core.cons.PRESENTATION import list_of_component_types
from Core.cons.GENERAL import list_of_notification_status
from Core.cons.TASK import list_of_task_types

class OrganizationForm(gis_form.ModelForm):
    class Meta:
        model = Organization
        fields = (
           'name',
           'phone',
           'email',
           'start_date',
           'title',
           'vision',
           'mission',
           'location',
        #    'geom',
        )
        widgets = {
            'location': LeafletWidget(),
            # 'geom': LeafletWidget(),
            'title': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
            'vision': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
            'mission': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
            'start_date': forms.DateInput(attrs={'class':'datepicker'}),
            }

class OrganizationUserForm(forms.ModelForm):
    class Meta:
        model = OrganizationUser
        fields = (
           'user',
        )

class DocumentForm(forms.ModelForm):

    file = forms.FileField(required=True)

    class Meta:
        model = Document
        fields = (
            'name',
            'file',
            'description',
        )
        widgets = { 
            'description': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

class DocumentUpdateForm(forms.ModelForm):    
    class Meta:
        model = Document
        fields = (
            'name',
            'description',
        )
        widgets = { 
            'description': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

class WF_ChartForm(forms.ModelForm):    
    class Meta:
        model = WF_Chart
        fields = (
            'name',
            'order',
        )

class Wf_Action_First_Step_Form(forms.ModelForm):
    
    category = forms.ChoiceField(choices=list_of_action_categories().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)

    class Meta:
        model = WF_Action
        fields = (
            'category',
            'order'
        )

class Wf_Action_Questionnaire_Form(forms.ModelForm):
    
    executor_type = forms.ChoiceField(choices=list_of_executor_types().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)
    notification_type = forms.ChoiceField(choices=list_of_notification_types().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)

    class Meta:
        model = WF_Action
        fields = (
            'name',
            'duration',
            'detail',
            'executor_type',
            'notification_type',
            'order'
        )
        widgets = { 
            'executor_type': forms.RadioSelect(),
            'notification_type': forms.RadioSelect(),
            'detail': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

class Wf_Action_Procedure_Form(forms.ModelForm):
    
    executor_type = forms.ChoiceField(choices=list_of_executor_types().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)
    notification_type = forms.ChoiceField(choices=list_of_notification_types().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)

    class Meta:
        model = WF_Action
        fields = (
            'procedure',
            'duration',
            'detail',
            'executor_type',
            'notification_type',
            'order'
        )
        widgets = { 
            'executor_type': forms.RadioSelect(),
            'notification_type': forms.RadioSelect(),
            'detail': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

    def __init__(self, chart_id, *args, **kwargs):
        self.instance = kwargs.get('instance', None)
        super(Wf_Action_Procedure_Form, self).__init__(*args, **kwargs)
        self.fields['procedure'] = forms.ModelChoiceField(
            queryset=Procedure.objects.filter(component=WF_Chart.objects.get(pk=chart_id).component,support_workflow=True).all(),
            label=_('procedure'),
            widget=forms.RadioSelect,
            empty_label=None,
            required=True)

class WF_InputForm(forms.ModelForm):
    class Meta:
        model = WF_Input
        fields = (
            'title',
            'type',
            'required',
            'default',
            'order',
            'help',
        )
        widgets = {
            'required' : CheckboxInput(attrs={'class': 'required checkbox'}),
            'help': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

class WF_TrackForm(forms.ModelForm):
    class Meta:
        model = WF_Track
        fields = (
            'name',
            'order',
        )
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'required'}),
        }        

class WF_XForm(forms.Form):
    
    def __init__(self, request, action_id, *args, **kwargs):
        super(WF_XForm, self).__init__(*args, **kwargs)

        inputs = WF_Input.objects.filter(action_id=action_id).all()

        for input in inputs:

            list_inputs = []
            attributes = None

            if input.type == list_of_input_choices().MODELCHOICEFIELD:
                list_inputs.append("queryset=%s" % ('input.tracks.all()'))

            if input.title:

                if input.required:
                    list_inputs.append('label="%s (*)"' % (input.title))
                    list_inputs.append("required='required'")
                else:
                    list_inputs.append('label="%s "' % (input.title))
                    list_inputs.append("required=False")
            
            if input.type == list_of_input_choices().TEXTAREAFIELD:
                input.type = list_of_input_choices().CHARFIELD
                list_inputs.append("widget=forms.Textarea(attrs={'width':'100%'})")
            
            if input.help:
                list_inputs.append("help_text='%s'" % (input.help))

            if input.default:
                list_inputs.append("initial='%s'" % (input.default))


            try:
                self.fields["id_%s" % (input.pk)] = eval("forms.%s( %s )" % (input.type, ','.join(map(str, list_inputs))))
            except SyntaxError or TypeError:
                messages.add_message(request, messages.ERROR, ( '%s : %s' % (_('review your field : '), input.title)))


class WF_TaskForm(forms.Form):
    
    def __init__(self, request, requestObject, action_id, *args, **kwargs):
        super(WF_TaskForm, self).__init__(*args, **kwargs)

        initial_values = dict(WF_Data.objects.filter(
            request=requestObject,
            action=requestObject.action,
            task=requestObject.task
        ).values_list('input_id', 'value'))

        inputs = WF_Input.objects.filter(action_id=action_id).all()
        for input in inputs:

            list_inputs = []
            attributes = None

            if input.type == list_of_input_choices().MODELCHOICEFIELD:
                list_inputs.append("queryset=%s" % ('input.tracks.all()'))

            if input.title:

                if input.required:
                    list_inputs.append('label="%s (*)"' % (input.title))
                    list_inputs.append("required='required'")
                else:
                    list_inputs.append('label="%s "' % (input.title))
                    list_inputs.append("required=False")
            
            if input.type == list_of_input_choices().TEXTAREAFIELD:
                input.type = list_of_input_choices().CHARFIELD
                list_inputs.append("widget=forms.Textarea(attrs={'width':'100%'})")
            
            if input.help:
                list_inputs.append("help_text='%s'" % (input.help))

            if input.default:
                pass
                # list_inputs.append("initial='%s'" % ( initial_values[input.pk] if initial_values[input.pk] else input.default ))

            try:
                self.fields["id_%s" % (input.pk)] = eval("forms.%s( %s )" % (input.type, ','.join(map(str, list_inputs))))
                try:

Core/templates/Core_configuration/dumpDBConfirmation.html
{% extends "base/header/modal_header.html" %}
{% load i18n %}
{% load static %}
{% block modal-header %}{% trans 'update' %}{% endblock %}
{% block modal-body %}
<section class="delete">
    <p>{% trans 'dump database confirmation message' %}</p>
    <a href="{% url 'Core:dump-db-update' %}" class="btn btn-warning submit-link">{% trans 'confirm' %}</a>
</section>
{% endblock %}
{% block modal-footer %}{% endblock %}

Core/templates/Core_configuration/loadCoreModelDBConfirmation.html
{% extends "base/header/modal_header.html" %}
{% load i18n %}
{% load static %}
{% block modal-header %}{% trans 'update' %}{% endblock %}
{% block modal-body %}
<section class="delete">
    <p>{% trans 'load core model data Confirmation confirmation message' %}</p>
    <a href="{% url 'Core:load-core-model-data' %}" class="btn btn-warning submit-link">{% trans 'confirm' %}</a>
</section>
{% endblock %}
{% block modal-footer %}{% endblock %}

Core/templates/Core_configuration/loadDBConfirmation.html
{% extends "base/header/modal_header.html" %}
{% load i18n %}
{% load static %}
{% block modal-header %}{% trans 'update' %}{% endblock %}
{% block modal-body %}
<section class="delete">
    <p>{% trans 'load data from file to database confirmation message' %}</p>
    <a href="{% url 'Core:load-db-update' %}" class="btn btn-warning submit-link">{% trans 'confirm' %}</a>
</section>
{% endblock %}
{% block modal-footer %}{% endblock %}

Core/templates/Core_configuration/prepare_db_ideoms_to_in_translation_file.html
{% extends "base/header/modal_header.html" %}
{% load i18n %}
{% load static %}
{% block modal-header %}{% trans 'update' %}{% endblock %}
{% block modal-body %}
<section class="delete">
    <p>{% trans 'prepare db ideoms to in translation file update confirmation message' %}</p>
    <a href="{% url 'Core:prepare-db-ideoms-to-in-translation-file-update' %}" class="btn btn-warning submit-link">{% trans 'confirm' %}</a>
</section>
{% endblock %}
{% block modal-footer %}{% endblock %}

Core/templates/Core_configuration/show.html
{% extends "base/header/system_header.html" %}
{% load i18n %}
{% load static %}

{% block page_title %}{% trans 'Core' %}{% endblock %}

{% block crumbs %}
    <li class="breadcrumb-back"><a href="{% url 'Core:home'%}"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a></li>
    <li class="breadcrumb-back">{% trans 'Core' %}</li>
    <li class="breadcrumb-back">{% trans 'home' %}</li>
{% endblock %}

{% block content %}
    <section class="configuration">
        <table class="table">
            <tr>
                <td width="5%">1</td>
                <td width="20%">{% trans 'system preparation' %}</td>
                <td width="75%">
                    <a href="{% url 'Core:update-systemApps-confirmation' %}" data-toggle='modal' data-target='#modal' class="btn btn-sm sharp icon-only general-link">
                        <i class="fa fa-fas fa-cog" aria-hidden="true"></i> {% trans 'update' %}
                    </a>
                </td>
            </tr>
            {% comment %} <tr>
                <td>2</td>
                <td>{% trans 'dump data to files' %}</td>
                <td>
                    <a href="{% url 'Core:dump-db-confirmation' %}" data-toggle='modal' data-target='#modal' class="btn btn-sm sharp icon-only general-link">
                        <i class="fa fa-fas fa-cog" aria-hidden="true"></i> {% trans 'update' %}
                    </a>
                </td>
            </tr> {% endcomment %}
            {% comment %} <tr>
                <td>3</td>
                <td>{% trans 'prepare db ideoms to in translation file' %}</td>
                <td>
                    <a href="{% url 'Core:prepare-db-ideoms-to-in-translation-file' %}" data-toggle='modal' data-target='#modal' class="btn btn-sm sharp icon-only general-link">
                        <i class="fa fa-fas fa-cog" aria-hidden="true"></i> {% trans 'update' %}
                    </a>
                </td>
            </tr> {% endcomment %}
        </table>
    </section>
{% endblock %}

Core/templates/Core_configuration/updateSystemAppsConfirmation.html
{% extends "base/header/modal_header.html" %}
{% load i18n %}
{% load static %}
{% block modal-header %}{% trans 'update' %}{% endblock %}
{% block modal-body %}
<section class="delete">
    <p>{% trans 'system app update confirmation message' %}</p>
    <a href="{% url 'Core:system-apps-update' %}" class="btn btn-warning submit-link">{% trans 'confirm' %}</a>
</section>
{% endblock %}
{% block modal-footer %}{% endblock %}