Core/urls.py
from django.urls import path

app_name = 'Core'

urlpatterns = []

P001/urls.py
from django.urls import path
from P001.views import home, kashta, bladalnoor, batinjan, partenership

app_name = 'P001'

urlpatterns = [
    path('', home.show, name='home'),
    path('kashta/home', kashta.home, name='kashta-home'),
    path('bladalnoor/home', bladalnoor.home, name='bladalnoor-home'),
    path('batinjan/home', batinjan.home, name='batinjan-home'),
    path('partenership/home', partenership.home, name='partenership-home'),
]

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from P000.views import home

urlpatterns = [

    path('', home.show, name='website-home'),

    path('Core/', include('Core.urls')), # Core
    path('login/home/', include('P000.urls')), # P000
    path('user/dashboard/', include('P001.urls')), # P001
    path('admin/', admin.site.urls),
    path('i18n/', include('django.conf.urls.i18n')),
    path('api-auth/', include('rest_framework.urls')),
    path('accounts/', include('allauth.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

# Use static() to add url mapping to serve static files during development (only)

# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Core/forms.py
from django.contrib.gis import forms as gis_form
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.forms.fields import CheckboxInput

from colorful.fields import RGBColorField
from leaflet.forms.widgets import LeafletWidget

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from Core.models.Organization import Organization
from Core.models.OrganizationUser import OrganizationUser
from Core.models.Place import Place
from Core.models.Document import Document
from Core.models.WF_Chart import WF_Chart
from Core.models.WF_Action import WF_Action
from Core.models.WF_Input import WF_Input
from Core.models.WF_Track import WF_Track
from Core.models.WF_Data import WF_Data
from Core.models.WF_Dump import WF_Dump
from Core.models.SheetParagraph import SheetParagraph
from Core.models.Component import Component
from Core.models.Paragraph import Paragraph
from Core.models.Parameter import Parameter
from Core.models.Permit import Permit
from Core.models.Feature import Feature
from Core.models.Procedure import Procedure
from Core.models.Sheet import Sheet
from Core.models.Element import Element
from Core.models.Fact import Fact
from Core.models.Datum import Datum
from Core.models.Analyze import Analyze
from Core.models.Version import Version
from Core.models.Refinement import Refinement
from P003.models.Unit import Unit
from P003.models.Vacant import Vacant

from Core.cons.WORKFLOW import list_of_executor_types
from Core.cons.WORKFLOW import list_of_input_choices
from Core.cons.WORKFLOW import list_of_action_types
from Core.cons.WORKFLOW import list_of_executions_status
from Core.cons.WORKFLOW import list_of_action_categories
from Core.cons.WORKFLOW import list_of_notification_types
from Core.cons.PRESENTATION import list_of_component_types
from Core.cons.GENERAL import list_of_notification_status
from Core.cons.TASK import list_of_task_types

class OrganizationForm(gis_form.ModelForm):
    class Meta:
        model = Organization
        fields = (
           'name',
           'phone',
           'email',
           'start_date',
           'title',
           'vision',
           'mission',
           'location',
        #    'geom',
        )
        widgets = {
            'location': LeafletWidget(),
            # 'geom': LeafletWidget(),
            'title': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
            'vision': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
            'mission': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
            'start_date': forms.DateInput(attrs={'class':'datepicker'}),
            }

class OrganizationUserForm(forms.ModelForm):
    class Meta:
        model = OrganizationUser
        fields = (
           'user',
        )

class DocumentForm(forms.ModelForm):

    file = forms.FileField(required=True)

    class Meta:
        model = Document
        fields = (
            'name',
            'file',
            'description',
        )
        widgets = { 
            'description': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

class DocumentUpdateForm(forms.ModelForm):    
    class Meta:
        model = Document
        fields = (
            'name',
            'description',
        )
        widgets = { 
            'description': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

class WF_ChartForm(forms.ModelForm):    
    class Meta:
        model = WF_Chart
        fields = (
            'name',
            'order',
        )

class Wf_Action_First_Step_Form(forms.ModelForm):
    
    category = forms.ChoiceField(choices=list_of_action_categories().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)

    class Meta:
        model = WF_Action
        fields = (
            'category',
            'order'
        )

class Wf_Action_Questionnaire_Form(forms.ModelForm):
    
    executor_type = forms.ChoiceField(choices=list_of_executor_types().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)
    notification_type = forms.ChoiceField(choices=list_of_notification_types().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)

    class Meta:
        model = WF_Action
        fields = (
            'name',
            'duration',
            'detail',
            'executor_type',
            'notification_type',
            'order'
        )
        widgets = { 
            'executor_type': forms.RadioSelect(),
            'notification_type': forms.RadioSelect(),
            'detail': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

class Wf_Action_Procedure_Form(forms.ModelForm):
    
    executor_type = forms.ChoiceField(choices=list_of_executor_types().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)
    notification_type = forms.ChoiceField(choices=list_of_notification_types().iteratable,label=_('category'), widget=forms.RadioSelect,required=True)

    class Meta:
        model = WF_Action
        fields = (
            'procedure',
            'duration',
            'detail',
            'executor_type',
            'notification_type',
            'order'
        )
        widgets = { 
            'executor_type': forms.RadioSelect(),
            'notification_type': forms.RadioSelect(),
            'detail': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

    def __init__(self, chart_id, *args, **kwargs):
        self.instance = kwargs.get('instance', None)
        super(Wf_Action_Procedure_Form, self).__init__(*args, **kwargs)
        self.fields['procedure'] = forms.ModelChoiceField(
            queryset=Procedure.objects.filter(component=WF_Chart.objects.get(pk=chart_id).component,support_workflow=True).all(),
            label=_('procedure'),
            widget=forms.RadioSelect,
            empty_label=None,
            required=True)

class WF_InputForm(forms.ModelForm):
    class Meta:
        model = WF_Input
        fields = (
            'title',
            'type',
            'required',
            'default',
            'order',
            'help',
        )
        widgets = {
            'required' : CheckboxInput(attrs={'class': 'required checkbox'}),
            'help': forms.Textarea(attrs={'rows':3, 'class':'form-control'}),
        }

class WF_TrackForm(forms.ModelForm):
    class Meta:
        model = WF_Track
        fields = (
            'name',
            'order',
        )
        widgets = {
            'name' : forms.TextInput(attrs={'class': 'required'}),
        }        

class WF_XForm(forms.Form):
    
    def __init__(self, request, action_id, *args, **kwargs):
        super(WF_XForm, self).__init__(*args, **kwargs)

        inputs = WF_Input.objects.filter(action_id=action_id).all()

        for input in inputs:

            list_inputs = []
            attributes = None

            if input.type == list_of_input_choices().MODELCHOICEFIELD:
                list_inputs.append("queryset=%s" % ('input.tracks.all()'))

            if input.title:

                if input.required:
                    list_inputs.append('label="%s (*)"' % (input.title))
                    list_inputs.append("required='required'")
                else:
                    list_inputs.append('label="%s "' % (input.title))
                    list_inputs.append("required=False")
            
            if input.type == list_of_input_choices().TEXTAREAFIELD:
                input.type = list_of_input_choices().CHARFIELD
                list_inputs.append("widget=forms.Textarea(attrs={'width':'100%'})")
            
            if input.help:
                list_inputs.append("help_text='%s'" % (input.help))

            if input.default:
                list_inputs.append("initial='%s'" % (input.default))


            try:
                self.fields["id_%s" % (input.pk)] = eval("forms.%s( %s )" % (input.type, ','.join(map(str, list_inputs))))
            except SyntaxError or TypeError:
                messages.add_message(request, messages.ERROR, ( '%s : %s' % (_('review your field : '), input.title)))


class WF_TaskForm(forms.Form):
    
    def __init__(self, request, requestObject, action_id, *args, **kwargs):
        super(WF_TaskForm, self).__init__(*args, **kwargs)

        initial_values = dict(WF_Data.objects.filter(
            request=requestObject,
            action=requestObject.action,
            task=requestObject.task
        ).values_list('input_id', 'value'))

        inputs = WF_Input.objects.filter(action_id=action_id).all()
        for input in inputs:

            list_inputs = []
            attributes = None

            if input.type == list_of_input_choices().MODELCHOICEFIELD:
                list_inputs.append("queryset=%s" % ('input.tracks.all()'))

            if input.title:

                if input.required:
                    list_inputs.append('label="%s (*)"' % (input.title))
                    list_inputs.append("required='required'")
                else:
                    list_inputs.append('label="%s "' % (input.title))
                    list_inputs.append("required=False")
            
            if input.type == list_of_input_choices().TEXTAREAFIELD:
                input.type = list_of_input_choices().CHARFIELD
                list_inputs.append("widget=forms.Textarea(attrs={'width':'100%'})")
            
            if input.help:
                list_inputs.append("help_text='%s'" % (input.help))

            if input.default:
                pass
                # list_inputs.append("initial='%s'" % ( initial_values[input.pk] if initial_values[input.pk] else input.default ))

            try:
                self.fields["id_%s" % (input.pk)] = eval("forms.%s( %s )" % (input.type, ','.join(map(str, list_inputs))))
                try:

Core/templates/Core_tasks/dashboard.html
{% extends "base/header/browse_header.html" %}
{% load i18n %}
{% load static %}
{% load general_tags %}
{% load workflow_tags %}

{% block crumbs %}
    <li class="breadcrumb-back"><a href="{{ back_url_path }}"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a></li>
    <li class="breadcrumb-back">{% trans 'workflow library' %}</li>
    <li class="breadcrumb-back">{{ task.request }}</li>
{% endblock %}
{% block content %}
<section class="send-request">
    {% if task.action.pk == task.request.action.pk %}
        <div class="row">
            <div class="col-lg-12">
                <span class="pull-right">
                    {% RequestMoveBackward requestObject=task.request %}
                    &nbsp;|&nbsp;
                    {% RequestMoveForward requestObject=task.request %}
                </span>
            </div>
        </div>
        <hr>
    {% endif %}
    <div class="row">
        <div class="col-lg-6">
            {% RequestData requestObject=task.request %}
        </div>
        <div class="col-lg-6">
            {% if task.action.pk == task.request.action.pk %}
                {% ActionTaskForm requestObject=task.request action_id=task.request.action.pk %}
            {% else %}
                {% comment %} {% BrowseModelData modelObject=task %} {% endcomment %}
            {% endif %}
        </div>
    </div>
    {% RequestDocuments requestObject=task.request %}
    {% RequestLog requestObject=task.request back_url=back_url %}
</section>
{% endblock %}
{% block footer %}
    {% comment %} {% WorkflowChartDiagram action_id=start_action_pk current_id=task.request.action.pk containerId='chart-container' %}     {% endcomment %}
{% endblock %}

Core/templates/Core_tasks/project_task_dashboard.html
{% extends "base/header/browse_header.html" %}
{% load i18n %}
{% load static %}
{% load general_tags %}
{% block page_title %}{% trans 'Core' %}{% endblock %}
{% block crumbs %}
    {% comment %} <li class="breadcrumb-back"><a href="{% url 'Core:project-dashboard' project_id=project.pk %}"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a></li> {% endcomment %}
    <li class="breadcrumb-back"><a href="{{ back_url_path }}"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a></li>
    <li class="breadcrumb-back">{{ project }}</li>
    <li class="breadcrumb-back">{{ task }}</li>
{% endblock %}
{% block content %}
<section class="add">
    <div class="row">
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans 'the task' %}</div>
                <div class="panel-body">
                    <p>{{ task.description }}</p>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-default">
                <div class="panel-heading">{% trans 'more details' %}</div>
                <div class="panel-body">
                    {% BrowseModelData modelObject=task %}
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            {% if task.assigned_to.pk == request.user.pk and task.completion == OPEN %}
                <div class="panel panel-default">
                    <div class="panel-heading">{% trans 'task status' %}</div>
                    <div class="panel-body">
                        <form action="{% url 'Core:project-task-update-execution-status' task_id=task.pk back_url=back_url %}" method="POST">
                            {% csrf_token %}
                                <div class="form-group">
                                    {% for item in execution_status_list %}
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="execution_status" id="{{ item.0 }}" value="{{ item.0 }}" {% if task.execution_status == item.0 %} checked {% endif %}>{{ item.1 }}
                                        </label>
                                    </div>
                                    {% endfor %}
                                </div>
                            <button type="submit" class="btn btn-warning">{% trans 'update' %}</button>
                        </form>
                    </div>
                </div>
            {% endif %}
            {% if project.manager.pk == request.user.pk %}
                <div class="panel panel-default">
                    <div class="panel-heading">{% trans 'completion' %}</div>
                    <div class="panel-body">
                        <form action="{% url 'Core:project-task-update-completion' task_id=task.pk back_url=back_url %}" method="POST">
                            {% csrf_token %}
                                <div class="form-group">
                                    {% for item in completion_status_list %}
                                    <div class="radio">
                                        <label>
                                            <input type="radio" name="completion_status" id="{{ item.0 }}" value="{{ item.0 }}" {% if task.completion == item.0 %} checked {% endif %}>{% trans item.0 %}
                                        </label>
                                    </div>
                                    {% endfor %}
                                </div>
                            <button type="submit" class="btn btn-warning">{% trans 'update' %}</button>
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</section>

{% endblock %}

Core/templates/Core_tasks/show.html
{% extends "base/header/browse_header.html" %}
{% load i18n %}
{% load static %}
{% load general_tags %}
{% block page_title %}{% trans 'tasks dashboard' %}{% endblock %}
{% block crumbs %}
    <li class="breadcrumb-back"><a href="{% url 'P001:home'%}"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a></li>
    <li class="breadcrumb-back">{% trans 'P001' %}</li>
    <li class="breadcrumb-back">{{ request.user.get_full_name }}</li>
    <li class="breadcrumb-back">{% trans 'tasks dashboard' %}</li>
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-3">
            {% tasks_menu %}
        </div>
        <div class="col-lg-9">
            <table class="table">
                <tr>
                    <td width="5%">&nbsp;</td>
                    <td width="20%">{% trans 'the task' %}</td>
                    <td width="20%">{% trans 'assigned by' %}&nbsp;/&nbsp;{% trans 'assigned_date' %}</td>
                    <td width="20%">{% trans 'duration' %}</td>
                    <td width="15%">{% trans 'settings' %}</td>
                </tr>
                {% for task in tasks %}
                    <tr>
                        <td></td>
                        <td>{{ task }}</td>
                        <td>{{ task.assigned_by.get_full_name }}&nbsp;/&nbsp;{{ task.assigned_date }}</td>
                        <td>{{ task.get_duration }}</td>
                        <td>
                            <a href="{% url 'Core:task-redirection' task_id=task.pk %}" class="general-link">
                                {% trans 'workflow task dashboard' %}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

Core/templates/Core_tasks/workflow_task_dashboard.html
{% extends "base/header/browse_header.html" %}
{% load i18n %}
{% load static %}
{% load general_tags %}
{% load workflow_tags %}
{% block crumbs %}
    <li class="breadcrumb-back"><a href="{{ back_url_path }}"><i class="fa fa-arrow-circle-right" aria-hidden="true"></i></a></li>
    <li class="breadcrumb-back">{% trans 'workflow library' %}</li>
    <li class="breadcrumb-back">{{ wf_request }}</li>
{% endblock %}
{% block content %}
<section class="send-request">
    {% if task.action.pk == wf_request.action.pk and wf_request.action.category == 'QUESTIONNAIRE' %}
        <div class="row">
            <div class="col-lg-12">
                <span class="pull-{{ LANGUAGE_END }}">
                    {% RequestMoveBackward requestObject=wf_request %}
                    &nbsp;|&nbsp;
                    {% RequestMoveForward requestObject=wf_request %}
                </span>
            </div>
        </div>
        <hr>
    {% endif %}
    <div class="row">
        <div class="col-lg-6">
            {% RequestData requestObject=wf_request %}
        </div>
        <div class="col-lg-6">
            {% if task.action.pk == wf_request.action.pk %}
                {% ActionTaskForm requestObject=wf_request action_id=wf_request.action.pk %}
            {% else %}
                {% BrowseModelData modelObject=task %}
            {% endif %}
        </div>
    </div>
    {% RequestDocuments requestObject=wf_request %}
    {% RequestLog requestObject=wf_request back_url=back_url %}
</section>
{% endblock %}
{% block footer %}
    {% WorkflowChartDiagram action_id=start_action_pk current_id=wf_request.action.pk containerId='chart-container' %}    
{% endblock %}